"""
Schema indexes and virtual table definitions for code_analysis database.

Author: Vasiliy Zdanovskiy
email: vasilyvz@gmail.com
"""

from typing import Any, Dict, List


def get_schema_indexes() -> List[Dict[str, Any]]:
    """Return the list of index definitions for schema sync."""
    return [
        {
            "name": "idx_projects_root_path",
            "table": "projects",
            "columns": ["root_path"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_files_project",
            "table": "files",
            "columns": ["project_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_files_path",
            "table": "files",
            "columns": ["path"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_files_deleted",
            "table": "files",
            "columns": ["deleted"],
            "unique": False,
            "where_clause": "deleted = 1",
        },
        {
            "name": "idx_files_deleted_project_id",
            "table": "files",
            "columns": ["deleted", "project_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_runtime_lock_sessions_pid",
            "table": "runtime_lock_sessions",
            "columns": ["pid"],
            "unique": True,
            "where_clause": None,
        },
        {
            "name": "idx_file_advisory_lock_leases_file",
            "table": "file_advisory_lock_leases",
            "columns": ["project_id", "file_path"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_file_advisory_lock_leases_session",
            "table": "file_advisory_lock_leases",
            "columns": ["session_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_classes_name",
            "table": "classes",
            "columns": ["name"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_classes_file",
            "table": "classes",
            "columns": ["file_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_methods_name",
            "table": "methods",
            "columns": ["name"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_methods_class",
            "table": "methods",
            "columns": ["class_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_functions_name",
            "table": "functions",
            "columns": ["name"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_functions_file",
            "table": "functions",
            "columns": ["file_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_imports_file",
            "table": "imports",
            "columns": ["file_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_imports_name",
            "table": "imports",
            "columns": ["name"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_issues_type",
            "table": "issues",
            "columns": ["issue_type"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_issues_file",
            "table": "issues",
            "columns": ["file_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_issues_project",
            "table": "issues",
            "columns": ["project_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_issues_class_id",
            "table": "issues",
            "columns": ["class_id"],
            "unique": False,
            "where_clause": "class_id IS NOT NULL",
        },
        {
            "name": "idx_issues_method_id",
            "table": "issues",
            "columns": ["method_id"],
            "unique": False,
            "where_clause": "method_id IS NOT NULL",
        },
        {
            "name": "idx_issues_function_id",
            "table": "issues",
            "columns": ["function_id"],
            "unique": False,
            "where_clause": "function_id IS NOT NULL",
        },
        {
            "name": "idx_usages_file",
            "table": "usages",
            "columns": ["file_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_usages_target",
            "table": "usages",
            "columns": ["target_type", "target_name"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_usages_class_name",
            "table": "usages",
            "columns": ["target_class", "target_name"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_entity_cross_ref_caller_class",
            "table": "entity_cross_ref",
            "columns": ["caller_class_id"],
            "unique": False,
            "where_clause": "caller_class_id IS NOT NULL",
        },
        {
            "name": "idx_entity_cross_ref_caller_method",
            "table": "entity_cross_ref",
            "columns": ["caller_method_id"],
            "unique": False,
            "where_clause": "caller_method_id IS NOT NULL",
        },
        {
            "name": "idx_entity_cross_ref_caller_function",
            "table": "entity_cross_ref",
            "columns": ["caller_function_id"],
            "unique": False,
            "where_clause": "caller_function_id IS NOT NULL",
        },
        {
            "name": "idx_entity_cross_ref_callee_class",
            "table": "entity_cross_ref",
            "columns": ["callee_class_id"],
            "unique": False,
            "where_clause": "callee_class_id IS NOT NULL",
        },
        {
            "name": "idx_entity_cross_ref_callee_method",
            "table": "entity_cross_ref",
            "columns": ["callee_method_id"],
            "unique": False,
            "where_clause": "callee_method_id IS NOT NULL",
        },
        {
            "name": "idx_entity_cross_ref_callee_function",
            "table": "entity_cross_ref",
            "columns": ["callee_function_id"],
            "unique": False,
            "where_clause": "callee_function_id IS NOT NULL",
        },
        {
            "name": "idx_entity_cross_ref_file",
            "table": "entity_cross_ref",
            "columns": ["file_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_code_content_file",
            "table": "code_content",
            "columns": ["file_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_code_content_entity",
            "table": "code_content",
            "columns": ["entity_type", "entity_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_ast_trees_file",
            "table": "ast_trees",
            "columns": ["file_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_ast_trees_project",
            "table": "ast_trees",
            "columns": ["project_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_ast_trees_hash",
            "table": "ast_trees",
            "columns": ["ast_hash"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_vector_index_project",
            "table": "vector_index",
            "columns": ["project_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_vector_index_entity",
            "table": "vector_index",
            "columns": ["entity_type", "entity_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_vector_index_vector_id",
            "table": "vector_index",
            "columns": ["vector_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_code_chunks_file",
            "table": "code_chunks",
            "columns": ["file_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_code_chunks_project",
            "table": "code_chunks",
            "columns": ["project_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_code_chunks_uuid",
            "table": "code_chunks",
            "columns": ["chunk_uuid"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_code_chunks_vector",
            "table": "code_chunks",
            "columns": ["vector_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_code_chunks_not_vectorized",
            "table": "code_chunks",
            "columns": ["project_id", "created_at", "id"],
            "unique": False,
            "where_clause": "vector_id IS NULL",
        },
        {
            "name": "idx_code_chunks_created_at",
            "table": "code_chunks",
            "columns": ["created_at"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_code_chunks_project_embedding_model",
            "table": "code_chunks",
            "columns": ["project_id"],
            "unique": False,
            "where_clause": "embedding_model IS NOT NULL",
        },
        {
            "name": "idx_files_updated_at",
            "table": "files",
            "columns": ["updated_at"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_files_needs_indexing",
            "table": "files",
            "columns": ["project_id", "updated_at"],
            "unique": False,
            "where_clause": "(deleted = 0 OR deleted IS NULL) AND needs_chunking = 1",
        },
        {
            "name": "idx_code_duplicates_project",
            "table": "code_duplicates",
            "columns": ["project_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_code_duplicates_hash",
            "table": "code_duplicates",
            "columns": ["duplicate_hash"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_duplicate_occurrences_duplicate",
            "table": "duplicate_occurrences",
            "columns": ["duplicate_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_duplicate_occurrences_file",
            "table": "duplicate_occurrences",
            "columns": ["file_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_file_watcher_stats_start_time",
            "table": "file_watcher_stats",
            "columns": ["cycle_start_time"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_vectorization_stats_start_time",
            "table": "vectorization_stats",
            "columns": ["cycle_start_time"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_indexing_worker_stats_start_time",
            "table": "indexing_worker_stats",
            "columns": ["cycle_start_time"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_file_tree_snapshots_file_id",
            "table": "file_tree_snapshots",
            "columns": ["file_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_file_tree_snapshots_project_id",
            "table": "file_tree_snapshots",
            "columns": ["project_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_file_tree_snapshot_nodes_snapshot_id",
            "table": "file_tree_snapshot_nodes",
            "columns": ["snapshot_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_file_tree_snapshot_nodes_parent",
            "table": "file_tree_snapshot_nodes",
            "columns": ["snapshot_id", "parent_node_id"],
            "unique": False,
            "where_clause": None,
        },
        # Indexes for clear_project_data batch deletes (WHERE project_id / file_id / snapshot_id)
        {
            "name": "idx_cst_trees_project",
            "table": "cst_trees",
            "columns": ["project_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_cst_trees_file",
            "table": "cst_trees",
            "columns": ["file_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_indexing_errors_project",
            "table": "indexing_errors",
            "columns": ["project_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_comprehensive_analysis_results_project",
            "table": "comprehensive_analysis_results",
            "columns": ["project_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_comprehensive_analysis_results_file",
            "table": "comprehensive_analysis_results",
            "columns": ["file_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_file_tree_snapshot_roots_snapshot_id",
            "table": "file_tree_snapshot_roots",
            "columns": ["snapshot_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_project_activity_locks_lease_until",
            "table": "project_activity_locks",
            "columns": ["lease_until"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_runtime_lock_sessions_pid",
            "table": "runtime_lock_sessions",
            "columns": ["pid"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_file_advisory_lock_leases_file",
            "table": "file_advisory_lock_leases",
            "columns": ["project_id", "file_path"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_file_advisory_lock_leases_session",
            "table": "file_advisory_lock_leases",
            "columns": ["session_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_client_sessions_last_active",
            "table": "client_sessions",
            "columns": ["last_active_at"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_session_file_locks_session",
            "table": "session_file_locks",
            "columns": ["session_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_session_file_locks_file",
            "table": "session_file_locks",
            "columns": ["project_id", "file_id"],
            "unique": False,
            "where_clause": None,
        },
        {
            "name": "idx_role_permissions_role",
            "table": "role_permissions",
            "columns": ["role_id"],
            "unique": False,
            "where_clause": None,
        },
    ]


def get_schema_virtual_tables() -> List[Dict[str, Any]]:
    """Return the list of virtual table definitions (e.g. FTS5) for schema sync."""
    return [
        {
            "name": "code_content_fts",
            "type": "fts5",
            "columns": ["entity_type", "entity_name", "content", "docstring"],
            "options": {"content_rowid": "rowid", "content": "code_content"},
        }
    ]
