"""
PostgreSQL DDL generation from structured schema definition.

Mirrors schema_sync_sql.generate_create_table_sql with types and defaults
suitable for PostgreSQL (IDENTITY, DOUBLE PRECISION, BYTEA, Julian defaults).

Author: Vasiliy Zdanovskiy
email: vasilyvz@gmail.com
"""

from __future__ import annotations

from typing import Any, Dict

from .schema_sync_models import IndexDef


def _map_column_type(sqlite_type: str) -> str:
    t = (sqlite_type or "TEXT").upper().strip()
    if t in ("UUID",):
        return "UUID"
    if t in ("TEXT",):
        return "TEXT"
    if t in ("INTEGER", "INT"):
        return "INTEGER"
    if t in ("REAL", "FLOAT", "DOUBLE"):
        return "DOUBLE PRECISION"
    if t in ("BLOB",):
        return "BYTEA"
    if t in ("BOOLEAN", "BOOL"):
        return "BOOLEAN"
    return sqlite_type


def _default_sqlite_to_postgres(default_val: str, *, pg_type: str) -> str:
    s = default_val.strip()
    if pg_type == "BOOLEAN" and s in ("0", "1"):
        return "FALSE" if s == "0" else "TRUE"
    if s == "julianday('now')":
        return "(EXTRACT(JULIAN FROM CURRENT_TIMESTAMP))"
    if not s.startswith("(") and "(" in s and "julianday" not in s:
        return f"({s})"
    return s


def generate_create_table_sql_postgres(
    schema_definition: Dict[str, Any],
    table_name: str,
    *,
    relax_cst_node_id_not_null: bool = False,
) -> str:
    """Generate CREATE TABLE for PostgreSQL from schema definition."""
    table_def = schema_definition["tables"][table_name]
    columns = table_def["columns"]
    pk_cols = [col["name"] for col in columns if col.get("primary_key")]
    composite_pk = len(pk_cols) > 1

    col_defs: list[str] = []
    for col in columns:
        pg_type = _map_column_type(col["type"])
        name = col["name"]
        is_ai = bool(col.get("autoincrement"))
        is_pk = bool(col.get("primary_key"))
        skip_generic_default = False

        if is_pk and not composite_pk and is_ai and pg_type == "INTEGER":
            col_sql = f"{name} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        elif is_pk and not composite_pk and pg_type == "TEXT":
            col_sql = f"{name} TEXT PRIMARY KEY"
        elif is_pk and not composite_pk and pg_type == "UUID":
            # INSERTs omit id; PostgreSQL requires DEFAULT gen_random_uuid() on new DBs.
            if col.get("default") is not None:
                col_sql = f"{name} UUID PRIMARY KEY"
            else:
                col_sql = f"{name} UUID PRIMARY KEY DEFAULT gen_random_uuid()"
                skip_generic_default = True
        elif is_pk and not composite_pk and pg_type == "INTEGER" and not is_ai:
            col_sql = f"{name} INTEGER PRIMARY KEY"
        else:
            col_sql = f"{name} {pg_type}"
            if is_pk and not composite_pk:
                col_sql += " PRIMARY KEY"

        is_relaxed_cst_col = (
            relax_cst_node_id_not_null and col.get("name") == "cst_node_id"
        )
        if (
            col.get("not_null")
            and not col.get("primary_key")
            and not is_relaxed_cst_col
        ):
            col_sql += " NOT NULL"

        if not skip_generic_default and col.get("default") is not None:
            default_val = col["default"]
            if isinstance(default_val, str):
                dv = _default_sqlite_to_postgres(default_val, pg_type=pg_type)
                col_sql += f" DEFAULT {dv}"
            else:
                col_sql += f" DEFAULT {default_val}"

        col_defs.append(col_sql)

    if composite_pk:
        col_defs.append(f"PRIMARY KEY ({', '.join(pk_cols)})")

    for fk in table_def.get("foreign_keys", []):
        fk_cols = ", ".join(fk["columns"])
        ref_cols = ", ".join(fk["references_columns"])
        on_delete = fk.get("on_delete", "")
        fk_sql = (
            f"FOREIGN KEY ({fk_cols}) REFERENCES {fk['references_table']}({ref_cols})"
        )
        if on_delete:
            fk_sql += f" ON DELETE {on_delete}"
        col_defs.append(fk_sql)

    for uc in table_def.get("unique_constraints", []):
        uc_cols = ", ".join(uc["columns"])
        col_defs.append(f"UNIQUE ({uc_cols})")

    return f"CREATE TABLE IF NOT EXISTS {table_name} ({', '.join(col_defs)})"


def _index_where_sqlite_to_pg(where_clause: str) -> str:
    """Map SQLite-style boolean comparisons in partial indexes to PostgreSQL BOOLEAN.

    SQLite schema may use INTEGER 0/1 for legacy columns; PostgreSQL uses BOOLEAN
    for ``deleted`` (and similar). ``needs_chunking`` remains INTEGER in the
    logical schema, so ``needs_chunking = 1`` is left unchanged for PostgreSQL.
    """
    w = where_clause
    w = w.replace("deleted = 1", "deleted IS TRUE")
    w = w.replace("deleted = 0", "deleted IS FALSE")
    return w


def generate_create_index_sql_postgres(index_def: IndexDef) -> str:
    """CREATE INDEX for PostgreSQL (IF NOT EXISTS, partial indexes supported)."""
    unique_str = "UNIQUE " if index_def.unique else ""
    columns_str = ", ".join(index_def.columns)
    if index_def.where_clause:
        pg_where = _index_where_sqlite_to_pg(index_def.where_clause)
        where_part = f" WHERE {pg_where}"
    else:
        where_part = ""
    return (
        f"CREATE {unique_str}INDEX IF NOT EXISTS {index_def.name} "
        f"ON {index_def.table} ({columns_str}){where_part}"
    )
