"""
Structured schema definition for code_analysis database.

Exposes SCHEMA_VERSION, MIGRATION_METHODS, and get_schema_definition() for
sync_schema and schema comparison. Extracted from base.py to keep file size under limit.

Author: Vasiliy Zdanovskiy
email: vasilyvz@gmail.com
"""

from typing import Any, Callable, Dict

# Schema version constant
SCHEMA_VERSION = (
    "1.5.0"  # file_tree_snapshots, file_tree_snapshot_roots, file_tree_snapshot_nodes
)

# Migration methods registry: version -> migration function
# Each migration function receives driver instance and performs version-specific migrations
MIGRATION_METHODS: Dict[str, Callable[[Any], None]] = {
    # Register migration methods here
    # Format: "version": lambda driver: driver._migration_method_name()
    # Note: Methods are defined in SQLiteDriver, registry is here for centralization
}


def get_schema_definition() -> Dict[str, Any]:
    """
    Return structured schema definition for synchronization.

    Used by SchemaComparator and by RPC client when initializing an empty database.
    Returns a dict with version, tables, indexes, virtual_tables, migration_methods.
    """
    return {
        "version": SCHEMA_VERSION,
        "tables": {
            "db_settings": {
                "columns": [
                    {
                        "name": "key",
                        "type": "TEXT",
                        "not_null": True,
                        "primary_key": True,
                    },
                    {"name": "value", "type": "TEXT", "not_null": True},
                    {
                        "name": "updated_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [],
                "unique_constraints": [],
                "check_constraints": [],
            },
            "watch_dirs": {
                "columns": [
                    {
                        "name": "id",
                        "type": "TEXT",
                        "not_null": True,
                        "primary_key": True,
                    },
                    {"name": "name", "type": "TEXT", "not_null": False},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                    {
                        "name": "updated_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [],
                "unique_constraints": [],
                "check_constraints": [],
            },
            "watch_dir_paths": {
                "columns": [
                    {
                        "name": "watch_dir_id",
                        "type": "TEXT",
                        "not_null": True,
                        "primary_key": True,
                    },
                    {"name": "absolute_path", "type": "TEXT", "not_null": False},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                    {
                        "name": "updated_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["watch_dir_id"],
                        "references_table": "watch_dirs",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    }
                ],
                "unique_constraints": [],
                "check_constraints": [],
            },
            "projects": {
                "columns": [
                    {
                        "name": "id",
                        "type": "TEXT",
                        "not_null": True,
                        "primary_key": True,
                    },
                    {"name": "root_path", "type": "TEXT", "not_null": True},
                    {"name": "name", "type": "TEXT", "not_null": False},
                    {"name": "comment", "type": "TEXT", "not_null": False},
                    {"name": "watch_dir_id", "type": "TEXT", "not_null": False},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                    {
                        "name": "updated_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["watch_dir_id"],
                        "references_table": "watch_dirs",
                        "references_columns": ["id"],
                        "on_delete": "SET NULL",
                    }
                ],
                "unique_constraints": [{"columns": ["root_path"]}],
                "check_constraints": [],
            },
            "files": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "project_id", "type": "TEXT", "not_null": True},
                    {"name": "watch_dir_id", "type": "TEXT", "not_null": False},
                    {"name": "path", "type": "TEXT", "not_null": True},
                    {"name": "relative_path", "type": "TEXT", "not_null": False},
                    {"name": "lines", "type": "INTEGER", "not_null": False},
                    {"name": "last_modified", "type": "REAL", "not_null": False},
                    {"name": "has_docstring", "type": "BOOLEAN", "not_null": False},
                    {
                        "name": "deleted",
                        "type": "BOOLEAN",
                        "not_null": False,
                        "default": "0",
                    },
                    {"name": "original_path", "type": "TEXT", "not_null": False},
                    {"name": "version_dir", "type": "TEXT", "not_null": False},
                    {
                        "name": "needs_chunking",
                        "type": "INTEGER",
                        "not_null": False,
                        "default": "0",
                    },
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                    {
                        "name": "updated_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["project_id"],
                        "references_table": "projects",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["watch_dir_id"],
                        "references_table": "watch_dirs",
                        "references_columns": ["id"],
                        "on_delete": "SET NULL",
                    },
                ],
                "unique_constraints": [{"columns": ["project_id", "path"]}],
                "check_constraints": [],
            },
            "classes": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "file_id", "type": "INTEGER", "not_null": True},
                    {"name": "name", "type": "TEXT", "not_null": True},
                    {"name": "line", "type": "INTEGER", "not_null": True},
                    {"name": "end_line", "type": "INTEGER", "not_null": False},
                    {"name": "cst_node_id", "type": "TEXT", "not_null": False},
                    {"name": "docstring", "type": "TEXT", "not_null": False},
                    {"name": "bases", "type": "TEXT", "not_null": False},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["file_id"],
                        "references_table": "files",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    }
                ],
                "unique_constraints": [{"columns": ["file_id", "name", "line"]}],
                "check_constraints": [],
            },
            "methods": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "class_id", "type": "INTEGER", "not_null": True},
                    {"name": "name", "type": "TEXT", "not_null": True},
                    {"name": "line", "type": "INTEGER", "not_null": True},
                    {"name": "end_line", "type": "INTEGER", "not_null": False},
                    {"name": "cst_node_id", "type": "TEXT", "not_null": False},
                    {"name": "args", "type": "TEXT", "not_null": False},
                    {"name": "docstring", "type": "TEXT", "not_null": False},
                    {
                        "name": "is_abstract",
                        "type": "BOOLEAN",
                        "not_null": False,
                        "default": "0",
                    },
                    {
                        "name": "has_pass",
                        "type": "BOOLEAN",
                        "not_null": False,
                        "default": "0",
                    },
                    {
                        "name": "has_not_implemented",
                        "type": "BOOLEAN",
                        "not_null": False,
                        "default": "0",
                    },
                    {"name": "complexity", "type": "INTEGER", "not_null": False},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["class_id"],
                        "references_table": "classes",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    }
                ],
                "unique_constraints": [{"columns": ["class_id", "name", "line"]}],
                "check_constraints": [],
            },
            "functions": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "file_id", "type": "INTEGER", "not_null": True},
                    {"name": "name", "type": "TEXT", "not_null": True},
                    {"name": "line", "type": "INTEGER", "not_null": True},
                    {"name": "end_line", "type": "INTEGER", "not_null": False},
                    {"name": "cst_node_id", "type": "TEXT", "not_null": False},
                    {"name": "args", "type": "TEXT", "not_null": False},
                    {"name": "docstring", "type": "TEXT", "not_null": False},
                    {"name": "complexity", "type": "INTEGER", "not_null": False},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["file_id"],
                        "references_table": "files",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    }
                ],
                "unique_constraints": [{"columns": ["file_id", "name", "line"]}],
                "check_constraints": [],
            },
            "entity_cross_ref": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "caller_class_id", "type": "INTEGER", "not_null": False},
                    {"name": "caller_method_id", "type": "INTEGER", "not_null": False},
                    {
                        "name": "caller_function_id",
                        "type": "INTEGER",
                        "not_null": False,
                    },
                    {"name": "callee_class_id", "type": "INTEGER", "not_null": False},
                    {"name": "callee_method_id", "type": "INTEGER", "not_null": False},
                    {
                        "name": "callee_function_id",
                        "type": "INTEGER",
                        "not_null": False,
                    },
                    {"name": "ref_type", "type": "TEXT", "not_null": True},
                    {"name": "file_id", "type": "INTEGER", "not_null": False},
                    {"name": "line", "type": "INTEGER", "not_null": False},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["caller_class_id"],
                        "references_table": "classes",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["caller_method_id"],
                        "references_table": "methods",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["caller_function_id"],
                        "references_table": "functions",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["callee_class_id"],
                        "references_table": "classes",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["callee_method_id"],
                        "references_table": "methods",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["callee_function_id"],
                        "references_table": "functions",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["file_id"],
                        "references_table": "files",
                        "references_columns": ["id"],
                        "on_delete": "SET NULL",
                    },
                ],
                "unique_constraints": [],
                "check_constraints": [],
            },
            "imports": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "file_id", "type": "INTEGER", "not_null": True},
                    {"name": "name", "type": "TEXT", "not_null": True},
                    {"name": "module", "type": "TEXT", "not_null": False},
                    {"name": "import_type", "type": "TEXT", "not_null": True},
                    {"name": "line", "type": "INTEGER", "not_null": True},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["file_id"],
                        "references_table": "files",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    }
                ],
                "unique_constraints": [],
                "check_constraints": [],
            },
            "issues": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "file_id", "type": "INTEGER", "not_null": False},
                    {"name": "project_id", "type": "TEXT", "not_null": False},
                    {"name": "class_id", "type": "INTEGER", "not_null": False},
                    {"name": "function_id", "type": "INTEGER", "not_null": False},
                    {"name": "method_id", "type": "INTEGER", "not_null": False},
                    {"name": "issue_type", "type": "TEXT", "not_null": True},
                    {"name": "line", "type": "INTEGER", "not_null": False},
                    {"name": "description", "type": "TEXT", "not_null": False},
                    {"name": "metadata", "type": "TEXT", "not_null": False},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["file_id"],
                        "references_table": "files",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["project_id"],
                        "references_table": "projects",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["class_id"],
                        "references_table": "classes",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["function_id"],
                        "references_table": "functions",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["method_id"],
                        "references_table": "methods",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                ],
                "unique_constraints": [],
                "check_constraints": [],
            },
            "usages": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "file_id", "type": "INTEGER", "not_null": True},
                    {"name": "line", "type": "INTEGER", "not_null": True},
                    {"name": "usage_type", "type": "TEXT", "not_null": True},
                    {"name": "target_type", "type": "TEXT", "not_null": True},
                    {"name": "target_class", "type": "TEXT", "not_null": False},
                    {"name": "target_name", "type": "TEXT", "not_null": True},
                    {"name": "context", "type": "TEXT", "not_null": False},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["file_id"],
                        "references_table": "files",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    }
                ],
                "unique_constraints": [],
                "check_constraints": [],
            },
            "code_content": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "file_id", "type": "INTEGER", "not_null": True},
                    {"name": "entity_type", "type": "TEXT", "not_null": True},
                    {"name": "entity_id", "type": "INTEGER", "not_null": False},
                    {"name": "entity_name", "type": "TEXT", "not_null": False},
                    {"name": "content", "type": "TEXT", "not_null": True},
                    {"name": "docstring", "type": "TEXT", "not_null": False},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["file_id"],
                        "references_table": "files",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    }
                ],
                "unique_constraints": [],
                "check_constraints": [],
            },
            "ast_trees": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "file_id", "type": "INTEGER", "not_null": True},
                    {"name": "project_id", "type": "TEXT", "not_null": True},
                    {"name": "ast_json", "type": "TEXT", "not_null": True},
                    {"name": "ast_hash", "type": "TEXT", "not_null": True},
                    {"name": "file_mtime", "type": "REAL", "not_null": True},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                    {
                        "name": "updated_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["file_id"],
                        "references_table": "files",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["project_id"],
                        "references_table": "projects",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                ],
                "unique_constraints": [{"columns": ["file_id", "ast_hash"]}],
                "check_constraints": [],
            },
            "cst_trees": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "file_id", "type": "INTEGER", "not_null": True},
                    {"name": "project_id", "type": "TEXT", "not_null": True},
                    {"name": "cst_code", "type": "TEXT", "not_null": True},
                    {"name": "cst_hash", "type": "TEXT", "not_null": True},
                    {"name": "file_mtime", "type": "REAL", "not_null": True},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                    {
                        "name": "updated_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["file_id"],
                        "references_table": "files",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["project_id"],
                        "references_table": "projects",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                ],
                "unique_constraints": [{"columns": ["file_id", "cst_hash"]}],
                "check_constraints": [],
            },
            "vector_index": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "project_id", "type": "TEXT", "not_null": True},
                    {"name": "entity_type", "type": "TEXT", "not_null": True},
                    {"name": "entity_id", "type": "INTEGER", "not_null": True},
                    {"name": "vector_id", "type": "INTEGER", "not_null": True},
                    {"name": "vector_dim", "type": "INTEGER", "not_null": True},
                    {"name": "embedding_model", "type": "TEXT", "not_null": False},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["project_id"],
                        "references_table": "projects",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    }
                ],
                "unique_constraints": [
                    {"columns": ["project_id", "entity_type", "entity_id"]}
                ],
                "check_constraints": [],
            },
            "code_chunks": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "file_id", "type": "INTEGER", "not_null": True},
                    {"name": "project_id", "type": "TEXT", "not_null": True},
                    {"name": "chunk_uuid", "type": "TEXT", "not_null": True},
                    {"name": "chunk_type", "type": "TEXT", "not_null": True},
                    {"name": "chunk_text", "type": "TEXT", "not_null": True},
                    {"name": "chunk_ordinal", "type": "INTEGER", "not_null": False},
                    {"name": "vector_id", "type": "INTEGER", "not_null": False},
                    {"name": "embedding_model", "type": "TEXT", "not_null": False},
                    {"name": "bm25_score", "type": "REAL", "not_null": False},
                    {"name": "embedding_vector", "type": "TEXT", "not_null": False},
                    {"name": "token_count", "type": "INTEGER", "not_null": False},
                    {"name": "class_id", "type": "INTEGER", "not_null": False},
                    {"name": "function_id", "type": "INTEGER", "not_null": False},
                    {"name": "method_id", "type": "INTEGER", "not_null": False},
                    {"name": "line", "type": "INTEGER", "not_null": False},
                    {"name": "ast_node_type", "type": "TEXT", "not_null": False},
                    {"name": "source_type", "type": "TEXT", "not_null": False},
                    {
                        "name": "binding_level",
                        "type": "INTEGER",
                        "not_null": False,
                        "default": "0",
                    },
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                    {
                        "name": "updated_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["file_id"],
                        "references_table": "files",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["project_id"],
                        "references_table": "projects",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["class_id"],
                        "references_table": "classes",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["function_id"],
                        "references_table": "functions",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["method_id"],
                        "references_table": "methods",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                ],
                "unique_constraints": [{"columns": ["chunk_uuid"]}],
                "check_constraints": [],
            },
            "code_duplicates": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "project_id", "type": "TEXT", "not_null": True},
                    {"name": "duplicate_hash", "type": "TEXT", "not_null": True},
                    {"name": "similarity", "type": "REAL", "not_null": True},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["project_id"],
                        "references_table": "projects",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    }
                ],
                "unique_constraints": [{"columns": ["project_id", "duplicate_hash"]}],
                "check_constraints": [],
            },
            "duplicate_occurrences": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "duplicate_id", "type": "INTEGER", "not_null": True},
                    {"name": "file_id", "type": "INTEGER", "not_null": True},
                    {"name": "start_line", "type": "INTEGER", "not_null": True},
                    {"name": "end_line", "type": "INTEGER", "not_null": True},
                    {"name": "code_snippet", "type": "TEXT", "not_null": False},
                    {"name": "ast_node_id", "type": "INTEGER", "not_null": False},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["duplicate_id"],
                        "references_table": "code_duplicates",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["file_id"],
                        "references_table": "files",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                ],
                "unique_constraints": [],
                "check_constraints": [],
            },
            "comprehensive_analysis_results": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "file_id", "type": "INTEGER", "not_null": True},
                    {"name": "project_id", "type": "TEXT", "not_null": True},
                    {"name": "file_mtime", "type": "REAL", "not_null": True},
                    {"name": "results_json", "type": "TEXT", "not_null": True},
                    {"name": "summary_json", "type": "TEXT", "not_null": True},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                    {
                        "name": "updated_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["file_id"],
                        "references_table": "files",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["project_id"],
                        "references_table": "projects",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                ],
                "unique_constraints": [{"columns": ["file_id", "file_mtime"]}],
                "check_constraints": [],
            },
            "file_watcher_stats": {
                "columns": [
                    {
                        "name": "cycle_id",
                        "type": "TEXT",
                        "not_null": True,
                        "primary_key": True,
                    },
                    {
                        "name": "cycle_start_time",
                        "type": "REAL",
                        "not_null": True,
                    },
                    {"name": "cycle_end_time", "type": "REAL", "not_null": False},
                    {
                        "name": "files_total_at_start",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "files_added",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "files_processed",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "files_skipped",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "files_failed",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "files_changed",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "files_deleted",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "total_processing_time_seconds",
                        "type": "REAL",
                        "not_null": True,
                        "default": "0.0",
                    },
                    {
                        "name": "average_processing_time_seconds",
                        "type": "REAL",
                        "not_null": False,
                    },
                    {
                        "name": "last_updated",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                    {
                        "name": "current_project_id",
                        "type": "TEXT",
                        "not_null": False,
                    },
                ],
                "foreign_keys": [],
                "unique_constraints": [],
                "check_constraints": [],
            },
            "vectorization_stats": {
                "columns": [
                    {
                        "name": "cycle_id",
                        "type": "TEXT",
                        "not_null": True,
                        "primary_key": True,
                    },
                    {
                        "name": "cycle_start_time",
                        "type": "REAL",
                        "not_null": True,
                    },
                    {"name": "cycle_end_time", "type": "REAL", "not_null": False},
                    {
                        "name": "chunks_total_at_start",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "chunks_processed",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "chunks_skipped",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "chunks_failed",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "files_total_at_start",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "files_vectorized",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "total_processing_time_seconds",
                        "type": "REAL",
                        "not_null": True,
                        "default": "0.0",
                    },
                    {
                        "name": "average_processing_time_seconds",
                        "type": "REAL",
                        "not_null": False,
                    },
                    {
                        "name": "last_updated",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [],
                "unique_constraints": [],
                "check_constraints": [],
            },
            "indexing_worker_stats": {
                "columns": [
                    {
                        "name": "cycle_id",
                        "type": "TEXT",
                        "not_null": True,
                        "primary_key": True,
                    },
                    {
                        "name": "cycle_start_time",
                        "type": "REAL",
                        "not_null": True,
                    },
                    {"name": "cycle_end_time", "type": "REAL", "not_null": False},
                    {
                        "name": "files_total_at_start",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "files_indexed",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "files_failed",
                        "type": "INTEGER",
                        "not_null": True,
                        "default": "0",
                    },
                    {
                        "name": "total_processing_time_seconds",
                        "type": "REAL",
                        "not_null": True,
                        "default": "0.0",
                    },
                    {
                        "name": "average_processing_time_seconds",
                        "type": "REAL",
                        "not_null": False,
                    },
                    {
                        "name": "last_updated",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [],
                "unique_constraints": [],
                "check_constraints": [],
            },
            "file_tree_snapshots": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "file_id", "type": "INTEGER", "not_null": True},
                    {"name": "project_id", "type": "TEXT", "not_null": True},
                    {"name": "source_payload", "type": "TEXT", "not_null": True},
                    {"name": "file_mtime", "type": "REAL", "not_null": True},
                    {
                        "name": "created_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                    {
                        "name": "updated_at",
                        "type": "REAL",
                        "not_null": False,
                        "default": "julianday('now')",
                    },
                ],
                "foreign_keys": [
                    {
                        "columns": ["file_id"],
                        "references_table": "files",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                    {
                        "columns": ["project_id"],
                        "references_table": "projects",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                ],
                "unique_constraints": [{"columns": ["file_id"]}],
                "check_constraints": [],
            },
            "file_tree_snapshot_roots": {
                "columns": [
                    {
                        "name": "snapshot_id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                    },
                    {"name": "root_node_id", "type": "TEXT", "not_null": True},
                ],
                "foreign_keys": [
                    {
                        "columns": ["snapshot_id"],
                        "references_table": "file_tree_snapshots",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                ],
                "unique_constraints": [],
                "check_constraints": [],
            },
            "file_tree_snapshot_nodes": {
                "columns": [
                    {
                        "name": "id",
                        "type": "INTEGER",
                        "not_null": True,
                        "primary_key": True,
                        "autoincrement": True,
                    },
                    {"name": "snapshot_id", "type": "INTEGER", "not_null": True},
                    {"name": "node_id", "type": "TEXT", "not_null": True},
                    {"name": "parent_node_id", "type": "TEXT", "not_null": False},
                    {"name": "child_index", "type": "INTEGER", "not_null": True},
                ],
                "foreign_keys": [
                    {
                        "columns": ["snapshot_id"],
                        "references_table": "file_tree_snapshots",
                        "references_columns": ["id"],
                        "on_delete": "CASCADE",
                    },
                ],
                "unique_constraints": [
                    {"columns": ["snapshot_id", "node_id"]},
                    {"columns": ["snapshot_id", "parent_node_id", "child_index"]},
                ],
                "check_constraints": [],
            },
        },
        "indexes": [
            {
                "name": "idx_projects_root_path",
                "table": "projects",
                "columns": ["root_path"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_files_project",
                "table": "files",
                "columns": ["project_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_files_path",
                "table": "files",
                "columns": ["path"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_files_deleted",
                "table": "files",
                "columns": ["deleted"],
                "unique": False,
                "where_clause": "deleted = 1",
            },
            {
                "name": "idx_classes_name",
                "table": "classes",
                "columns": ["name"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_classes_file",
                "table": "classes",
                "columns": ["file_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_methods_name",
                "table": "methods",
                "columns": ["name"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_methods_class",
                "table": "methods",
                "columns": ["class_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_functions_name",
                "table": "functions",
                "columns": ["name"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_functions_file",
                "table": "functions",
                "columns": ["file_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_imports_file",
                "table": "imports",
                "columns": ["file_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_imports_name",
                "table": "imports",
                "columns": ["name"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_issues_type",
                "table": "issues",
                "columns": ["issue_type"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_issues_file",
                "table": "issues",
                "columns": ["file_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_issues_project",
                "table": "issues",
                "columns": ["project_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_usages_file",
                "table": "usages",
                "columns": ["file_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_usages_target",
                "table": "usages",
                "columns": ["target_type", "target_name"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_usages_class_name",
                "table": "usages",
                "columns": ["target_class", "target_name"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_entity_cross_ref_caller_class",
                "table": "entity_cross_ref",
                "columns": ["caller_class_id"],
                "unique": False,
                "where_clause": "caller_class_id IS NOT NULL",
            },
            {
                "name": "idx_entity_cross_ref_caller_method",
                "table": "entity_cross_ref",
                "columns": ["caller_method_id"],
                "unique": False,
                "where_clause": "caller_method_id IS NOT NULL",
            },
            {
                "name": "idx_entity_cross_ref_caller_function",
                "table": "entity_cross_ref",
                "columns": ["caller_function_id"],
                "unique": False,
                "where_clause": "caller_function_id IS NOT NULL",
            },
            {
                "name": "idx_entity_cross_ref_callee_class",
                "table": "entity_cross_ref",
                "columns": ["callee_class_id"],
                "unique": False,
                "where_clause": "callee_class_id IS NOT NULL",
            },
            {
                "name": "idx_entity_cross_ref_callee_method",
                "table": "entity_cross_ref",
                "columns": ["callee_method_id"],
                "unique": False,
                "where_clause": "callee_method_id IS NOT NULL",
            },
            {
                "name": "idx_entity_cross_ref_callee_function",
                "table": "entity_cross_ref",
                "columns": ["callee_function_id"],
                "unique": False,
                "where_clause": "callee_function_id IS NOT NULL",
            },
            {
                "name": "idx_entity_cross_ref_file",
                "table": "entity_cross_ref",
                "columns": ["file_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_code_content_file",
                "table": "code_content",
                "columns": ["file_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_code_content_entity",
                "table": "code_content",
                "columns": ["entity_type", "entity_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_ast_trees_file",
                "table": "ast_trees",
                "columns": ["file_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_ast_trees_project",
                "table": "ast_trees",
                "columns": ["project_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_ast_trees_hash",
                "table": "ast_trees",
                "columns": ["ast_hash"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_vector_index_project",
                "table": "vector_index",
                "columns": ["project_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_vector_index_entity",
                "table": "vector_index",
                "columns": ["entity_type", "entity_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_vector_index_vector_id",
                "table": "vector_index",
                "columns": ["vector_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_code_chunks_file",
                "table": "code_chunks",
                "columns": ["file_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_code_chunks_project",
                "table": "code_chunks",
                "columns": ["project_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_code_chunks_uuid",
                "table": "code_chunks",
                "columns": ["chunk_uuid"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_code_chunks_vector",
                "table": "code_chunks",
                "columns": ["vector_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_code_chunks_not_vectorized",
                "table": "code_chunks",
                "columns": ["project_id", "id"],
                "unique": False,
                "where_clause": "vector_id IS NULL",
            },
            {
                "name": "idx_code_chunks_created_at",
                "table": "code_chunks",
                "columns": ["created_at"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_code_chunks_project_embedding_model",
                "table": "code_chunks",
                "columns": ["project_id"],
                "unique": False,
                "where_clause": "embedding_model IS NOT NULL",
            },
            {
                "name": "idx_files_updated_at",
                "table": "files",
                "columns": ["updated_at"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_files_needs_indexing",
                "table": "files",
                "columns": ["project_id", "updated_at"],
                "unique": False,
                "where_clause": "(deleted = 0 OR deleted IS NULL) AND needs_chunking = 1",
            },
            {
                "name": "idx_code_duplicates_project",
                "table": "code_duplicates",
                "columns": ["project_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_code_duplicates_hash",
                "table": "code_duplicates",
                "columns": ["duplicate_hash"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_duplicate_occurrences_duplicate",
                "table": "duplicate_occurrences",
                "columns": ["duplicate_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_duplicate_occurrences_file",
                "table": "duplicate_occurrences",
                "columns": ["file_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_file_watcher_stats_start_time",
                "table": "file_watcher_stats",
                "columns": ["cycle_start_time"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_vectorization_stats_start_time",
                "table": "vectorization_stats",
                "columns": ["cycle_start_time"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_indexing_worker_stats_start_time",
                "table": "indexing_worker_stats",
                "columns": ["cycle_start_time"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_file_tree_snapshots_file_id",
                "table": "file_tree_snapshots",
                "columns": ["file_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_file_tree_snapshots_project_id",
                "table": "file_tree_snapshots",
                "columns": ["project_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_file_tree_snapshot_nodes_snapshot_id",
                "table": "file_tree_snapshot_nodes",
                "columns": ["snapshot_id"],
                "unique": False,
                "where_clause": None,
            },
            {
                "name": "idx_file_tree_snapshot_nodes_parent",
                "table": "file_tree_snapshot_nodes",
                "columns": ["snapshot_id", "parent_node_id"],
                "unique": False,
                "where_clause": None,
            },
        ],
        "virtual_tables": [
            {
                "name": "code_content_fts",
                "type": "fts5",
                "columns": ["entity_type", "entity_name", "content", "docstring"],
                "options": {"content_rowid": "rowid", "content": "code_content"},
            }
        ],
        "migration_methods": MIGRATION_METHODS,
    }
