"""
PostgreSQL DDL generation from structured schema definition.

Mirrors schema_sync_sql.generate_create_table_sql with types and defaults
suitable for PostgreSQL (IDENTITY, DOUBLE PRECISION, BYTEA, Julian defaults).

Author: Vasiliy Zdanovskiy
email: vasilyvz@gmail.com
"""

from __future__ import annotations

import re
from typing import Any, Dict, Match, Optional, Set

from .schema_sync_models import IndexDef

# Matches a bare `<identifier> = 0` / `<identifier> = 1` comparison, word-bounded so
# it does not partially match inside a longer identifier (e.g. `is_deleted = 1` vs a
# hypothetical `deleted = 1` substring search).
_BOOL_EQ_INT_RE = re.compile(r"\b(?P<col>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?P<val>0|1)\b")


def _map_column_type(sqlite_type: str) -> str:
    """Return map column type."""
    t = (sqlite_type or "TEXT").upper().strip()
    if t in ("UUID",):
        return "UUID"
    if t in ("TEXT",):
        return "TEXT"
    if t in ("INTEGER", "INT"):
        return "INTEGER"
    if t in ("REAL", "FLOAT", "DOUBLE"):
        return "DOUBLE PRECISION"
    if t in ("BLOB",):
        return "BYTEA"
    if t in ("BOOLEAN", "BOOL"):
        return "BOOLEAN"
    return sqlite_type


def _default_sqlite_to_postgres(default_val: str, *, pg_type: str) -> str:
    """Return default sqlite to postgres."""
    s = default_val.strip()
    if pg_type == "BOOLEAN" and s in ("0", "1"):
        return "FALSE" if s == "0" else "TRUE"
    if s == "julianday('now')":
        return "(EXTRACT(JULIAN FROM CURRENT_TIMESTAMP))"
    if not s.startswith("(") and "(" in s and "julianday" not in s:
        return f"({s})"
    return s


def generate_create_table_sql_postgres(
    schema_definition: Dict[str, Any],
    table_name: str,
    *,
    relax_cst_node_id_not_null: bool = False,
) -> str:
    """Generate CREATE TABLE for PostgreSQL from schema definition."""
    table_def = schema_definition["tables"][table_name]
    columns = table_def["columns"]
    pk_cols = [col["name"] for col in columns if col.get("primary_key")]
    composite_pk = len(pk_cols) > 1

    col_defs: list[str] = []
    for col in columns:
        pg_type = _map_column_type(col["type"])
        name = col["name"]
        is_ai = bool(col.get("autoincrement"))
        is_pk = bool(col.get("primary_key"))
        skip_generic_default = False

        if is_pk and not composite_pk and is_ai and pg_type == "INTEGER":
            col_sql = f"{name} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        elif is_pk and not composite_pk and pg_type == "TEXT":
            col_sql = f"{name} TEXT PRIMARY KEY"
        elif is_pk and not composite_pk and pg_type == "UUID":
            # INSERTs omit id; PostgreSQL requires DEFAULT gen_random_uuid() on new DBs.
            if col.get("default") is not None:
                col_sql = f"{name} UUID PRIMARY KEY"
            else:
                col_sql = f"{name} UUID PRIMARY KEY DEFAULT gen_random_uuid()"
                skip_generic_default = True
        elif is_pk and not composite_pk and pg_type == "INTEGER" and not is_ai:
            col_sql = f"{name} INTEGER PRIMARY KEY"
        else:
            col_sql = f"{name} {pg_type}"
            if is_pk and not composite_pk:
                col_sql += " PRIMARY KEY"

        is_relaxed_cst_col = (
            relax_cst_node_id_not_null and col.get("name") == "cst_node_id"
        )
        if (
            col.get("not_null")
            and not col.get("primary_key")
            and not is_relaxed_cst_col
        ):
            col_sql += " NOT NULL"

        if not skip_generic_default and col.get("default") is not None:
            default_val = col["default"]
            if isinstance(default_val, str):
                dv = _default_sqlite_to_postgres(default_val, pg_type=pg_type)
                col_sql += f" DEFAULT {dv}"
            else:
                col_sql += f" DEFAULT {default_val}"

        col_defs.append(col_sql)

    if composite_pk:
        col_defs.append(f"PRIMARY KEY ({', '.join(pk_cols)})")

    tables = schema_definition.get("tables", {})

    for fk in table_def.get("foreign_keys", []):
        ref_table = fk["references_table"]
        ref_cols = list(fk.get("references_columns") or [])
        ref_table_def = tables.get(ref_table)
        if ref_table_def:
            ref_pk_cols = [
                col["name"]
                for col in ref_table_def.get("columns", [])
                if col.get("primary_key")
            ]
            ref_unique_sets = {
                tuple(uc.get("columns", []))
                for uc in ref_table_def.get("unique_constraints", [])
                if uc.get("columns")
            }
            valid_ref_sets = set(ref_unique_sets)
            if ref_pk_cols:
                valid_ref_sets.add(tuple(ref_pk_cols))
            # PostgreSQL: FK must reference a PRIMARY KEY or UNIQUE column set.
            # Composite watch_dirs PKs remain valid for scoped refs, while the legacy
            # files.watch_dir_id -> watch_dirs.id path stays valid because watch_dirs.id
            # is declared UNIQUE in the logical schema.
            if ref_cols and tuple(ref_cols) not in valid_ref_sets:
                continue
        fk_cols = ", ".join(fk["columns"])
        ref_cols_sql = ", ".join(ref_cols)
        on_delete = fk.get("on_delete", "")
        fk_sql = f"FOREIGN KEY ({fk_cols}) REFERENCES {ref_table}({ref_cols_sql})"
        if on_delete:
            fk_sql += f" ON DELETE {on_delete}"
        col_defs.append(fk_sql)

    for uc in table_def.get("unique_constraints", []):
        uc_cols = ", ".join(uc["columns"])
        col_defs.append(f"UNIQUE ({uc_cols})")

    return f"CREATE TABLE IF NOT EXISTS {table_name} ({', '.join(col_defs)})"


def _boolean_columns_for_table(
    schema_definition: Dict[str, Any], table_name: str
) -> Set[str]:
    """Return the set of column names typed BOOLEAN for one table in a schema definition."""
    table_def = schema_definition.get("tables", {}).get(table_name, {})
    return {
        col["name"]
        for col in table_def.get("columns", [])
        if (col.get("type") or "").upper().strip() in ("BOOLEAN", "BOOL")
    }


def _index_where_sqlite_to_pg(
    where_clause: str,
    boolean_columns: Optional[Set[str]] = None,
) -> str:
    """Map SQLite-style boolean comparisons in partial indexes to PostgreSQL BOOLEAN.

    SQLite schema uses INTEGER 0/1 literals for BOOLEAN columns (``deleted``,
    ``content_stale``, ...) inside partial-index WHERE clauses. PostgreSQL requires a
    genuine boolean comparison against a BOOLEAN column: ``some_bool_col = 1`` raises
    ``psycopg.errors.UndefinedFunction: operator does not exist: boolean = integer``
    (1.6.76 deploy incident #2, ``idx_files_content_stale``). ``needs_chunking``
    stays INTEGER in the logical schema, so ``needs_chunking = 1`` must be left
    unchanged for PostgreSQL — the two literal shapes are indistinguishable by text
    alone, hence ``boolean_columns`` (derived by the caller from the schema
    definition's column types for this index's table) drives which identifiers get
    rewritten, instead of hardcoding column names here.

    When ``boolean_columns`` is not supplied, fall back to the historically-known
    ``deleted`` column only, preserving the pre-fix behavior for any caller that has
    not been updated to pass the schema definition. Every live call site in this
    codebase (``postgres_schema_ddl.create_postgresql_indexes`` and the
    ``postgres_migrations`` idempotent-ensure helpers) passes it explicitly.
    """
    cols = boolean_columns if boolean_columns is not None else {"deleted"}

    def _rewrite(match: "Match[str]") -> str:
        col, val = match.group("col"), match.group("val")
        if col not in cols:
            return match.group(0)
        return f"{col} IS {'TRUE' if val == '1' else 'FALSE'}"

    return _BOOL_EQ_INT_RE.sub(_rewrite, where_clause)


def generate_create_index_sql_postgres(
    index_def: IndexDef,
    schema_definition: Optional[Dict[str, Any]] = None,
) -> str:
    """CREATE INDEX for PostgreSQL (IF NOT EXISTS, partial indexes supported).

    ``schema_definition``, when provided, is used to derive which columns of
    ``index_def.table`` are BOOLEAN so that ``<col> = 0/1`` literals in the WHERE
    clause are rewritten to valid PostgreSQL boolean comparisons (see
    ``_index_where_sqlite_to_pg``). Always pass it from a live caller.
    """
    unique_str = "UNIQUE " if index_def.unique else ""
    columns_str = ", ".join(index_def.columns)
    if index_def.where_clause:
        boolean_columns = None
        if schema_definition is not None:
            boolean_columns = _boolean_columns_for_table(
                schema_definition, index_def.table
            )
        pg_where = _index_where_sqlite_to_pg(index_def.where_clause, boolean_columns)
        where_part = f" WHERE {pg_where}"
    else:
        where_part = ""
    return (
        f"CREATE {unique_str}INDEX IF NOT EXISTS {index_def.name} "
        f"ON {index_def.table} ({columns_str}){where_part}"
    )
