"""
Author: Vasiliy Zdanovskiy
email: vasilyvz@gmail.com

Gravitational waves computation for gravitational effects in 7D phase field theory.

This module implements the calculation of gravitational waves
generated by VBP envelope dynamics, including strain tensor,
polarization modes, and frequency spectrum.

Theoretical Background:
    In 7D BVP theory, gravitational waves arise from the dynamics
    of the VBP envelope, not from spacetime curvature. They propagate
    at the phase velocity c_φ and are generated by envelope oscillations.

Mathematical Foundation:
    Gravitational wave observables via c_T=c_φ from envelope dynamics
    GW-1 amplitude law: |h|∝a^{-1} when Γ=K=0

Example:
    >>> wave_calc = VBPGravitationalWavesCalculator(domain, params)
    >>> oscillations = wave_calc.compute_phase_field_oscillations(envelope_solution)
"""

import numpy as np
from typing import Dict, Any, Tuple, Optional
from .gravity_waves_strain import GravityWavesStrainComputation
from .gravity_waves_spectrum import GravityWavesSpectrumComputation
from .gravity_waves_energy import GravityWavesEnergyComputation


class VBPGravitationalWavesCalculator:
    """
    Calculator for gravitational waves from VBP envelope dynamics.

    Physical Meaning:
        Computes gravitational waves generated by the dynamics
        of the VBP envelope, including strain tensor and
        polarization modes. Waves propagate at c_T=c_φ and
        follow GW-1 amplitude law.

    Mathematical Foundation:
        Implements gravitational wave calculations from envelope dynamics:
        strain tensor, amplitude, and frequency spectrum via c_T=c_φ
        GW-1 amplitude law: |h|∝a^{-1} when Γ=K=0
    """

    def __init__(self, domain: "Domain", params: Dict[str, Any]):
        """
        Initialize gravitational waves calculator.

        Physical Meaning:
            Sets up the computational framework for gravitational
            wave calculations with appropriate parameters.

        Args:
            domain: Computational domain
            params: Physical parameters
        """
        self.domain = domain
        self.params = params
        self._setup_wave_parameters()
        
        # Initialize helper classes
        self.strain_computation = GravityWavesStrainComputation(params)
        self.spectrum_computation = GravityWavesSpectrumComputation()
        self.energy_computation = GravityWavesEnergyComputation(domain, params)

    def _setup_wave_parameters(self) -> None:
        """
        Setup parameters for VBP gravitational wave calculations.

        Physical Meaning:
            Initializes parameters for gravitational wave
            calculations from VBP envelope dynamics including
            frequency range and detection sensitivity.
        """
        self.frequency_range = self.params.get("frequency_range", (1e-4, 1e3))  # Hz
        self.detection_sensitivity = self.params.get("detection_sensitivity", 1e-21)
        self.c_phi = self.params.get("c_phi", 1.0)  # Phase velocity c_φ
        self.c_T = self.c_phi  # Wave speed c_T = c_φ
        self.source_distance = self.params.get("source_distance", 1e6)  # meters

    def compute_phase_field_oscillations(
        self, envelope_solution: np.ndarray
    ) -> Dict[str, Any]:
        """
        Compute phase field oscillations from VBP envelope dynamics.

        Physical Meaning:
            Calculates phase field oscillations generated by the
            VBP envelope dynamics, including strain tensor,
            amplitude, and frequency spectrum. Oscillations propagate
            at c_T=c_φ and follow GW-1 amplitude law.

        Mathematical Foundation:
            Computes phase field oscillation observables from envelope dynamics:
            strain tensor, amplitude, and frequency spectrum via c_T=c_φ
            GW-1 amplitude law: |h|∝a^{-1} when Γ=K=0

        Args:
            envelope_solution: VBP envelope solution

        Returns:
            Dictionary containing gravitational wave properties
        """
        # Compute strain tensor from envelope dynamics
        strain_tensor = self.strain_computation.compute_strain_tensor_from_envelope(
            envelope_solution
        )

        # Compute wave amplitude with GW-1 law
        amplitude = self.strain_computation.compute_gw1_amplitude(strain_tensor)

        # Compute frequency spectrum
        frequency_spectrum = self.spectrum_computation.compute_frequency_spectrum(
            strain_tensor
        )

        # Compute polarization modes
        polarization = self.spectrum_computation.compute_polarization_modes(
            strain_tensor
        )

        # Compute wave energy
        wave_energy = self.energy_computation.compute_wave_energy(strain_tensor)

        return {
            "strain_tensor": strain_tensor,
            "amplitude": amplitude,
            "frequency_spectrum": frequency_spectrum,
            "polarization": polarization,
            "wave_energy": wave_energy,
            "c_T": self.c_T,
            "c_phi": self.c_phi,
        }


    def compute_detection_sensitivity(
        self, amplitude: float, frequency: float
    ) -> Dict[str, Any]:
        """
        Compute detection sensitivity for VBP gravitational waves.

        Physical Meaning:
            Calculates the detectability of gravitational waves
            from VBP envelope dynamics based on amplitude and frequency.
            Uses c_T=c_φ for wave propagation.

        Args:
            amplitude: Wave amplitude
            frequency: Wave frequency

        Returns:
            Dictionary containing detection information
        """
        # Compute signal-to-noise ratio
        snr = amplitude / self.detection_sensitivity

        # Determine detectability
        detectable = snr > 1.0

        # Compute detection probability
        detection_probability = min(1.0, snr / 10.0)

        return {
            "signal_to_noise_ratio": snr,
            "detectable": detectable,
            "detection_probability": detection_probability,
            "amplitude": amplitude,
            "frequency": frequency,
            "c_T": self.c_T,
            "c_phi": self.c_phi,
        }

