"""
CREATE / DROP TABLE helpers for PostgreSQL driver process.

Author: Vasiliy Zdanovskiy
email: vasilyvz@gmail.com
"""

from __future__ import annotations

from typing import Any, Dict

from ..exceptions import DriverOperationError


def _pg_type(sqlite_type: str) -> str:
    """Return pg type."""
    t = (sqlite_type or "TEXT").upper().strip()
    if t in ("TEXT",):
        return "TEXT"
    if t in ("INTEGER", "INT"):
        return "INTEGER"
    if t in ("REAL", "FLOAT", "DOUBLE"):
        return "DOUBLE PRECISION"
    if t in ("BLOB",):
        return "BYTEA"
    if t in ("BOOLEAN", "BOOL"):
        return "BOOLEAN"
    return sqlite_type


def run_create_table_postgres(conn: Any, schema: Dict[str, Any]) -> bool:
    """Create table from RPC-style schema dict (same shape as SQLite driver)."""
    table_name = schema.get("name")
    if not table_name:
        raise DriverOperationError("Table name is required in schema")

    columns = schema.get("columns", [])
    if not columns:
        raise DriverOperationError("At least one column is required")

    # Composite PK (>1 column flagged primary_key) must be a single table-level
    # constraint; two inline PRIMARY KEY columns are rejected by PostgreSQL
    # ("multiple primary keys for table are not allowed").
    pk_columns = [
        col.get("name") for col in columns if col.get("primary_key") and col.get("name")
    ]
    composite_pk = len(pk_columns) > 1

    column_defs: list[str] = []
    for col in columns:
        col_name = col.get("name")
        col_type = _pg_type(col.get("type", "TEXT"))
        nullable = col.get("nullable", True)
        default = col.get("default")
        primary_key = bool(col.get("primary_key", False))
        autoinc = col.get("autoincrement", False)
        inline_pk = primary_key and not composite_pk

        if inline_pk and autoinc and col_type == "INTEGER":
            col_def = f"{col_name} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        elif inline_pk and col_type == "TEXT":
            col_def = f"{col_name} TEXT PRIMARY KEY"
        elif inline_pk and col_type == "INTEGER":
            col_def = f"{col_name} INTEGER PRIMARY KEY"
        else:
            col_def = f"{col_name} {col_type}"
            if inline_pk:
                col_def += " PRIMARY KEY"

        if not nullable and not primary_key:
            col_def += " NOT NULL"

        if default is not None:
            if isinstance(default, str):
                if default == "julianday('now')":
                    col_def += " DEFAULT (EXTRACT(JULIAN FROM CURRENT_TIMESTAMP))"
                elif "(" not in default:
                    col_def += f" DEFAULT '{default}'"
                else:
                    col_def += f" DEFAULT ({default})"
            else:
                col_def += f" DEFAULT {default}"

        column_defs.append(col_def)

    # Composite primary key as a single table-level constraint.
    if composite_pk:
        column_defs.append(f"PRIMARY KEY ({', '.join(pk_columns)})")

    constraints = schema.get("constraints", [])
    for constraint in constraints:
        if constraint.get("type") == "primary_key":
            cols = constraint.get("columns", [])
            if cols and not pk_columns:
                column_defs.append(f"PRIMARY KEY ({', '.join(cols)})")
        elif constraint.get("type") == "foreign_key":
            cols = constraint.get("columns", [])
            ref_table = constraint.get("references_table")
            ref_cols = constraint.get("references_columns", [])
            if cols and ref_table and ref_cols:
                column_defs.append(
                    f"FOREIGN KEY ({', '.join(cols)}) "
                    f"REFERENCES {ref_table} ({', '.join(ref_cols)})"
                )

    sql = f'CREATE TABLE IF NOT EXISTS "{table_name}" ({", ".join(column_defs)})'
    cur = conn.cursor()
    try:
        cur.execute(sql)
        conn.commit()
    except Exception as e:
        conn.rollback()
        raise DriverOperationError(f"Failed to create table: {e}") from e
    return True


def run_drop_table_postgres(conn: Any, table_name: str) -> bool:
    """Drop table (CASCADE for FK dependencies)."""
    sql = f'DROP TABLE IF EXISTS "{table_name}" CASCADE'
    cur = conn.cursor()
    try:
        cur.execute(sql)
        conn.commit()
    except Exception as e:
        conn.rollback()
        raise DriverOperationError(f"Failed to drop table: {e}") from e
    return True
